# common makefile directives for linux and win32 build

CC?=gcc
CXX?=g++
CFLAGS+=-Ibme -Iasm -O3 -Wall -fno-common
CXXFLAGS+=-Ibme -Iasm -O3 -Wall -fpermissive
DATAFILE?=./bme/datafile
DAT2INC?=./bme/dat2inc
STRIP?=strip
STRIP_FAIL_OK?=
VIDEO_PKGS=libavformat libavcodec libavutil libswscale
VIDEO_PKG_CONFIG_LIBS?=--libs

ifeq ($(GTULTRA_VIDEO),1)
VIDEO_CFLAGS:=$(shell pkg-config --cflags $(VIDEO_PKGS))
VIDEO_LIBS:=$(shell pkg-config $(VIDEO_PKG_CONFIG_LIBS) $(VIDEO_PKGS))
override CFLAGS+=-DGTULTRA_VIDEO $(VIDEO_CFLAGS)
override CXXFLAGS+=-DGTULTRA_VIDEO $(VIDEO_CFLAGS)
override LIBS+=$(VIDEO_LIBS)
GTULTRA_VIDEO_OBJS=gvideo.o
endif

GTULTRA_APP_OBJS=goatdata.o gt2stereo.o gsong.o gorder.o gpattern.o ginstr.o gtable.o gplay.o gdisplay.o gtabledisplay.o \
gfile.o greloc.o ghelp.o gsound.o gconsole.o gsid.o ginfo.o gmidi.o gundo.o gchareditor.o RtMidi.o gmidiselect.o gpaletteeditor.o gfkeys.o \
$(GTULTRA_VIDEO_OBJS) \
resid/envelope.o resid/extfilt.o resid/filter.o resid/pot.o resid/sid.o resid/wave.o resid/wave6581__ST.o \
resid/wave6581_P_T.o resid/wave6581_PS_.o resid/wave6581_PST.o resid/wave8580__ST.o resid/wave8580_P_T.o \
resid/wave8580_PS_.o resid/wave8580_PST.o resid/voice.o \
resid-fp/envelopefp.o resid-fp/extfiltfp.o resid-fp/filterfp.o resid-fp/potfp.o resid-fp/sidfp.o \
resid-fp/wavefp.o resid-fp/voicefp.o \
asm/asmtab.o asm/chnkpool.o asm/expr.o asm/lexyy.o asm/log.o asm/membuf.o asm/membufio.o asm/namedbuf.o asm/parse.o \
asm/pc.o asm/vec.o \
bme/bme_gfx.o bme/bme_snd.o bme/bme_win.o bme/bme_mou.o bme/bme_kbd.o bme/bme_io.o bme/bme_end.o bme/bme.o

EXE=	$(PREFIX)gtultra$(SUFFIX) \
	$(PREFIX)gt2reloc$(SUFFIX) \
	$(PREFIX)gtasm$(SUFFIX) \
	$(PREFIX)ins2snd2$(SUFFIX) \
	$(PREFIX)ss2stereo$(SUFFIX) \
	$(PREFIX)mod2sng2$(SUFFIX)

all: $(EXE)

ifndef CUSTOM_GTULTRA_TARGET
$(PREFIX)gtultra$(SUFFIX): $(GTULTRA_APP_OBJS)
	$(CXX) -o $@ $^ $(LIBS)
	$(STRIP_FAIL_OK)$(STRIP) $@
endif


# it would be nice not having to link things like resid, however the source is
# not ready for that
$(PREFIX)gt2reloc$(SUFFIX): goatdata.o gt2reloc.o gsong.o gorder.o gpattern.o ginstr.o gtable.o gplay.o gdisplay.o \
	gfile.o ghelp.o gsound.o gconsole.o gsid.o ginfo.o gmidi.o gundo.o gchareditor.o RtMidi.o gmidiselect.o gpaletteeditor.o gfkeys.o \
	$(GTULTRA_VIDEO_OBJS) \
resid/envelope.o resid/extfilt.o resid/filter.o resid/pot.o resid/sid.o resid/wave.o resid/wave6581__ST.o \
resid/wave6581_P_T.o resid/wave6581_PS_.o resid/wave6581_PST.o resid/wave8580__ST.o resid/wave8580_P_T.o \
resid/wave8580_PS_.o resid/wave8580_PST.o resid/voice.o \
resid-fp/envelopefp.o resid-fp/extfiltfp.o resid-fp/filterfp.o resid-fp/potfp.o resid-fp/sidfp.o \
resid-fp/wavefp.o resid-fp/voicefp.o \
asm/asmtab.o asm/chnkpool.o asm/expr.o asm/lexyy.o asm/log.o asm/membuf.o asm/membufio.o asm/namedbuf.o asm/parse.o \
asm/pc.o asm/vec.o \
bme/bme_gfx.o bme/bme_snd.o bme/bme_win.o bme/bme_mou.o bme/bme_kbd.o bme/bme_io.o bme/bme_end.o bme/bme.o
	$(CXX) -DGT2RELOC -o $@ $^ $(LIBS)
	$(STRIP_FAIL_OK)$(STRIP) $@

$(PREFIX)gtasm$(SUFFIX): gtasm.o \
asm/asmtab.o asm/chnkpool.o asm/expr.o asm/lexyy.o asm/log.o asm/membuf.o asm/membufio.o asm/namedbuf.o asm/parse.o \
asm/pc.o asm/vec.o
	$(CC) -o $@ $^
	$(STRIP_FAIL_OK)$(STRIP) $@

$(PREFIX)mod2sng2$(SUFFIX): mod2sng2.o bme/bme_end.o
	$(CC) -o $@ $^
	$(STRIP_FAIL_OK)$(STRIP) $@

$(PREFIX)ins2snd2$(SUFFIX): ins2snd2.o bme/bme_end.o
	$(CC) -o $@ $^
	$(STRIP_FAIL_OK)$(STRIP) $@

$(PREFIX)ss2stereo$(SUFFIX): ss2stereo.o bme/bme_end.o
	$(CC) -o $@ $^
	$(STRIP_FAIL_OK)$(STRIP) $@

gt2stereo.dat: player.s altplayer.s player3.s altplayer3.s player9.s altplayer9.s player12.s altplayer12.s  0default.gtp 1default.gtp 2default.gtp 3default.gtp 4default.gtp 5default.gtp 6default.gtp 7default.gtp 8default.gtp chargen.bin palette.bin cursor.bin bcursor.bin goattrk2.bmp gt2stereo.seq
	$(DATAFILE) $@ gt2stereo.seq

goatdata.c: gt2stereo.dat
	$(DAT2INC) $< $@

clean:
	$(RM) *.o *~
	$(RM) asm/*.o
	$(RM) bme/*.o
	$(RM) resid/*.o
	$(RM) resid-fp/*.o
	$(RM) $(EXE)

asm/lexyy.o: override CFLAGS += -Wno-unused-function
