#
# Win32 makefile
#

CC:=gcc
CXX:=g++
PREFIX=../win32/
SUFFIX=.exe
LIBS=-lmingw32 -lSDL2main -lSDL2.dll -lwinmm -mwindows -static-libstdc++ -static-libgcc -static 
RM=	-del
CUSTOM_GTULTRA_TARGET=1
STRIP_FAIL_OK=-

include makefile.common

$(PREFIX)gtultra$(SUFFIX): $(GTULTRA_APP_OBJS)
	windres gt2stereo.rc goaticon.o
	$(CXX) -o $@ $^ goaticon.o $(LIBS)
	$(STRIP_FAIL_OK)$(STRIP) $@
